export enum FetchActionKind {
  FETCH_REQUEST = 'FETCH_REQUEST',
  FETCH_SUCCESS = 'FETCH_SUCCESS',
  FETCH_FAIL = 'FETCH_FAIL',
  PAY_REQUEST = 'PAY_REQUEST',
  PAY_SUCCESS = 'PAY_SUCCESS',
  PAY_FAIL = 'PAY_FAIL',
  PAY_RESET = 'PAY_RESET',
}
